# Set to true to use lowercase keywords instead of uppercase.
lowercaseKeywords: false
connections:
  - alias: docker_postgres
    driver: postgresql
    proto: tcp
    user: postgres
    passwd: mysecretpassword
    host: 172.17.0.2
    port: 5432
    dbName: postgres
