--require('impatient')
--require('maps')
--require('plugins')
--
---- clean
--require('autocmd')
--require('treesitter')
--require('statusline')
--
---- possible slow
--require('lsp')
--require('settings')
